"""table_character

Revision ID: 42d1db236a40
Revises: 355378c19715
Create Date: 2025-04-15 16:04:51.078958

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42d1db236a40"
down_revision: Union[str, None] = "355378c19715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character",
        sa.Column(
            "id",
            app.models.types.ULIDType(),
            server_default=sa.text("gen_ulid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_outfit", sa.Text(), nullable=True),
        sa.Column(
            "extra_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character")
    # ### end Alembic commands ###
