"""table_disposition

Revision ID: a564964e5c4b
Revises: 42d1db236a40
Create Date: 2025-04-15 16:34:51.666612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'a564964e5c4b'
down_revision: Union[str, None] = '42d1db236a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposition',
    sa.Column('id', app.models.types.ULIDType(), server_default=sa.text('gen_ulid()'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.Column('character_id', app.models.types.ULIDType(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disposition')
    # ### end Alembic commands ###
