"""Initial revision

Revision ID: 355378c19715
Revises:
Create Date: 2025-03-15 02:36:20.609498

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "355378c19715"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS ulid"))
    # op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "pgx_ulid";'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('DROP EXTENSION IF EXISTS "ulid";'))
    # op.execute(sa.text('DROP EXTENSION IF EXISTS "pgx_ulid";'))
    # ### end Alembic commands ###
